[2022-07-25 19:31:26,108: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:31:26,109: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:31:26,109: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:31:26,110: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:31:26,512: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-25 19:31:26,520: INFO/MainProcess] mingle: searching for neighbors
[2022-07-25 19:31:27,543: INFO/MainProcess] mingle: all alone
[2022-07-25 19:31:27,568: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-25 19:34:00,053: INFO/MainProcess] Task ticker_management.tasks.callticker[40c52394-0718-4b4e-abf6-3db6ff325c87] received
[2022-07-25 19:41:24,363: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:41:24,364: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:41:24,364: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:41:24,365: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-25 19:41:24,819: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-25 19:41:24,825: INFO/MainProcess] mingle: searching for neighbors
[2022-07-25 19:41:25,842: INFO/MainProcess] mingle: all alone
[2022-07-25 19:41:25,866: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-26 10:26:17,339: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:26:17,340: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:26:17,340: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:26:17,340: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:26:17,706: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-26 10:26:17,712: INFO/MainProcess] mingle: searching for neighbors
[2022-07-26 10:26:18,728: INFO/MainProcess] mingle: all alone
[2022-07-26 10:26:18,752: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-26 10:26:18,865: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '4db8e0cb-84c0-412e-a470-7269cf6736b4', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '4db8e0cb-84c0-412e-a470-7269cf6736b4', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen75401@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-07-26 10:29:12,905: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:29:12,906: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:29:12,907: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:29:12,908: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 10:29:13,435: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-26 10:29:13,449: INFO/MainProcess] mingle: searching for neighbors
[2022-07-26 10:29:14,474: INFO/MainProcess] mingle: all alone
[2022-07-26 10:29:14,507: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-26 19:05:00,026: INFO/MainProcess] Task ticker_management.tasks.callticker[e84e9f64-b4cc-4ff6-b90a-ece3a9329c6d] received
[2022-07-26 19:52:54,219: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 19:52:54,219: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 19:52:54,220: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 19:52:54,220: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-26 19:52:54,413: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-26 19:52:54,416: INFO/MainProcess] mingle: searching for neighbors
[2022-07-26 19:52:55,426: INFO/MainProcess] mingle: all alone
[2022-07-26 19:52:55,440: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-27 10:29:59,635: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 10:29:59,656: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 10:29:59,656: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 10:29:59,656: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 10:30:00,012: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-27 10:30:00,017: INFO/MainProcess] mingle: searching for neighbors
[2022-07-27 10:30:01,029: INFO/MainProcess] mingle: all alone
[2022-07-27 10:30:01,087: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-27 10:30:01,215: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '83f05d92-5897-4fde-9a8e-2ff9d80ecbcd', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '83f05d92-5897-4fde-9a8e-2ff9d80ecbcd', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen5318@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-07-27 14:22:00,007: INFO/MainProcess] Task ticker_management.tasks.callticker[effee8df-7b8f-45d2-8544-80d13a7beeb9] received
[2022-07-27 14:25:00,005: INFO/MainProcess] Task ticker_management.tasks.callticker[f4df2069-ab5d-48cc-82cf-b32855a42195] received
[2022-07-27 19:46:53,384: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 19:46:53,384: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 19:46:53,384: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 19:46:53,384: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-27 19:46:53,574: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-27 19:46:53,576: INFO/MainProcess] mingle: searching for neighbors
[2022-07-27 19:46:54,587: INFO/MainProcess] mingle: all alone
[2022-07-27 19:46:54,602: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-28 00:00:00,049: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': '94dc45ae-8682-48f3-b19c-e1b0e04f990a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '94dc45ae-8682-48f3-b19c-e1b0e04f990a', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen18846@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-07-28 00:00:00,130: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '70abf740-4b50-44ae-907f-2495212c6774', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '70abf740-4b50-44ae-907f-2495212c6774', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen18846@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-07-28 00:00:00,196: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '097a167c-80b2-4aa0-b600-0a38c27d2dc3', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '097a167c-80b2-4aa0-b600-0a38c27d2dc3', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen18846@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-07-28 11:11:20,836: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 11:11:20,836: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 11:11:20,837: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 11:11:20,837: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 11:11:21,029: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-28 11:11:21,032: INFO/MainProcess] mingle: searching for neighbors
[2022-07-28 11:11:22,042: INFO/MainProcess] mingle: all alone
[2022-07-28 11:11:22,057: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-28 15:38:49,089: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:38:49,122: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:38:49,122: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:38:49,123: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:38:49,738: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-28 15:38:49,743: INFO/MainProcess] mingle: searching for neighbors
[2022-07-28 15:38:50,754: INFO/MainProcess] mingle: all alone
[2022-07-28 15:38:50,791: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-28 15:55:50,337: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:55:50,337: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:55:50,337: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:55:50,337: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-07-28 15:55:50,529: INFO/MainProcess] Connected to redis://127.0.0.1:6379//
[2022-07-28 15:55:50,531: INFO/MainProcess] mingle: searching for neighbors
[2022-07-28 15:55:51,544: INFO/MainProcess] mingle: all alone
[2022-07-28 15:55:51,559: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-07-29 00:00:00,048: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '7214b3d2-0344-4794-80f4-6e0605174295', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '7214b3d2-0344-4794-80f4-6e0605174295', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen7469@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-07-29 00:00:00,167: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': '65a3335c-c61d-4ed6-aa8f-bf16b85b10d1', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '65a3335c-c61d-4ed6-aa8f-bf16b85b10d1', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen7469@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-07-29 00:00:00,233: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': 'f35e7e6a-cf63-44c2-baec-ae4475eb67ea', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f35e7e6a-cf63-44c2-baec-ae4475eb67ea', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen7469@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-03 11:59:20,956: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 11:59:20,970: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 11:59:20,971: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 11:59:20,971: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 11:59:21,188: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2022-08-03 11:59:23,194: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2022-08-03 11:59:27,201: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2022-08-03 11:59:33,211: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 8.00 seconds... (4/100)

[2022-08-03 11:59:41,224: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 10.00 seconds... (5/100)

[2022-08-03 11:59:51,237: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 12.00 seconds... (6/100)

[2022-08-03 12:00:03,252: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 14.00 seconds... (7/100)

[2022-08-03 12:00:17,269: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 16.00 seconds... (8/100)

[2022-08-03 12:00:33,288: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 18.00 seconds... (9/100)

[2022-08-03 12:00:51,308: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 20.00 seconds... (10/100)

[2022-08-03 12:01:11,331: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 22.00 seconds... (11/100)

[2022-08-03 12:01:33,358: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 24.00 seconds... (12/100)

[2022-08-03 12:01:57,387: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 26.00 seconds... (13/100)

[2022-08-03 12:02:23,419: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 28.00 seconds... (14/100)

[2022-08-03 12:02:51,458: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 30.00 seconds... (15/100)

[2022-08-03 12:03:21,494: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:03:53,531: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:04:25,568: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:04:57,604: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:05:29,640: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:06:01,678: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:06:33,717: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:07:05,755: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:07:37,791: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:08:09,826: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:08:41,861: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:09:13,898: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:09:45,934: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:10:17,972: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:10:50,006: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:11:22,044: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:11:54,080: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:12:26,114: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:12:58,151: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:13:30,188: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:14:02,223: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:14:34,261: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:15:06,296: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:15:38,330: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:16:10,368: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:16:42,405: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:17:14,440: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:17:46,477: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:18:18,510: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:18:50,542: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:19:22,578: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:19:54,614: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:20:26,650: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:20:58,684: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:21:30,721: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:22:02,755: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:22:34,792: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:23:06,828: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:23:38,864: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:24:10,897: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:24:42,936: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:25:14,974: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:25:47,011: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:26:19,048: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:26:51,086: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:27:23,122: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:27:55,158: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:28:27,193: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:28:59,226: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:29:31,256: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:30:03,288: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:30:35,317: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:31:07,350: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:31:39,385: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:32:11,422: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:32:43,460: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:33:15,495: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:33:47,528: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:34:19,567: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:34:51,605: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:35:23,641: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:35:55,678: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:36:27,712: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:36:59,748: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:37:31,784: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:38:03,820: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:38:35,856: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:39:07,888: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:39:39,927: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:40:11,964: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:40:44,000: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:41:16,039: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:41:48,076: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:42:20,110: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:42:52,149: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:43:24,186: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:43:56,222: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:44:28,258: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:45:00,293: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:45:32,339: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:46:04,375: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:46:36,411: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:47:08,445: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:47:40,480: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 12:48:12,515: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:45:56,798: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 14:45:56,799: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 14:45:56,799: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 14:45:56,800: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 14:45:57,239: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2022-08-03 14:45:59,245: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2022-08-03 14:46:03,253: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2022-08-03 14:46:09,263: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 8.00 seconds... (4/100)

[2022-08-03 14:46:17,276: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 10.00 seconds... (5/100)

[2022-08-03 14:46:27,290: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 12.00 seconds... (6/100)

[2022-08-03 14:46:39,305: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 14.00 seconds... (7/100)

[2022-08-03 14:46:53,324: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 16.00 seconds... (8/100)

[2022-08-03 14:47:09,343: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 18.00 seconds... (9/100)

[2022-08-03 14:47:27,365: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 20.00 seconds... (10/100)

[2022-08-03 14:47:47,391: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 22.00 seconds... (11/100)

[2022-08-03 14:48:09,416: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 24.00 seconds... (12/100)

[2022-08-03 14:48:33,444: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 26.00 seconds... (13/100)

[2022-08-03 14:48:59,473: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 28.00 seconds... (14/100)

[2022-08-03 14:49:27,506: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 30.00 seconds... (15/100)

[2022-08-03 14:49:57,541: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:50:29,578: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:51:01,616: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:51:33,652: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:52:05,689: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:52:37,725: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:53:09,761: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:53:41,799: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:54:13,834: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:54:45,869: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:55:17,907: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:55:49,944: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:56:21,981: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:56:54,017: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:57:26,056: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:57:58,093: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:58:30,128: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:59:02,162: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 14:59:34,199: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:00:06,235: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:00:38,269: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:01:10,305: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:01:42,342: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:02:14,378: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:02:46,416: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:03:18,454: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:03:50,490: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:04:22,526: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:04:54,561: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:05:26,596: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:05:58,631: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:06:30,667: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:07:02,705: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:07:34,752: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:08:06,788: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:08:38,824: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:09:10,859: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:09:42,895: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:10:14,932: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:10:46,968: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:11:19,003: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:11:51,041: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:12:23,078: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:12:55,113: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:13:27,149: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:13:59,186: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:14:31,224: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:15:03,261: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:15:35,296: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:16:07,330: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:16:39,364: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:17:11,401: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:17:43,436: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:18:15,472: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:18:47,509: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:19:19,545: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:19:51,577: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:20:23,613: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:20:55,651: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:21:27,687: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:21:59,723: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:22:31,757: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:23:03,793: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:23:35,831: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:24:07,868: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:24:39,903: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:25:11,939: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:25:43,973: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:26:16,006: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:26:48,042: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:27:20,080: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:27:52,119: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:28:24,157: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:28:56,194: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:29:28,231: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:30:00,267: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:30:32,305: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:31:04,339: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:31:36,375: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:32:08,409: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:32:40,445: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:33:12,482: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:33:44,519: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:34:16,554: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:34:48,591: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:51:25,732: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 15:51:25,734: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 15:51:25,734: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 15:51:25,735: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 15:51:26,320: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2022-08-03 15:51:28,326: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2022-08-03 15:51:32,333: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 6.00 seconds... (3/100)

[2022-08-03 15:51:38,344: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 8.00 seconds... (4/100)

[2022-08-03 15:51:46,356: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 10.00 seconds... (5/100)

[2022-08-03 15:51:56,370: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 12.00 seconds... (6/100)

[2022-08-03 15:52:08,384: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 14.00 seconds... (7/100)

[2022-08-03 15:52:22,402: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 16.00 seconds... (8/100)

[2022-08-03 15:52:38,424: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 18.00 seconds... (9/100)

[2022-08-03 15:52:56,443: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 20.00 seconds... (10/100)

[2022-08-03 15:53:16,474: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 22.00 seconds... (11/100)

[2022-08-03 15:53:38,500: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 24.00 seconds... (12/100)

[2022-08-03 15:54:02,528: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 26.00 seconds... (13/100)

[2022-08-03 15:54:28,558: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 28.00 seconds... (14/100)

[2022-08-03 15:54:56,592: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 30.00 seconds... (15/100)

[2022-08-03 15:55:26,626: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:55:58,669: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:56:30,706: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:57:02,741: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:57:34,790: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:58:06,832: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:58:38,870: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:59:10,908: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 15:59:42,944: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:00:14,976: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:00:47,020: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:01:19,067: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:01:51,102: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:02:23,138: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:02:55,179: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:03:27,220: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:03:59,254: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:04:31,293: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:05:03,329: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:05:35,365: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:06:07,400: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:06:39,436: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:07:11,475: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:07:43,505: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:08:15,537: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:08:47,571: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:09:19,606: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:09:51,641: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:10:23,689: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:10:55,725: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:11:27,761: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:11:59,798: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:12:31,833: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:13:03,870: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:13:35,904: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:14:07,938: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:14:39,974: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:15:12,012: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:15:44,055: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:16:16,092: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:16:48,127: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:17:20,162: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:17:52,202: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:18:24,238: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:18:56,274: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:19:28,309: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:20:00,365: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:20:32,399: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:21:04,434: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:21:36,470: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:22:08,506: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:22:40,541: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:23:12,577: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:23:44,612: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:24:16,646: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:24:48,685: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:25:20,721: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:25:52,756: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:26:24,792: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:26:56,823: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:27:28,859: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:28:00,898: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:28:32,933: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:29:04,969: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:29:37,005: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:30:09,041: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:30:41,079: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:31:13,115: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:31:45,152: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:32:17,201: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:32:49,249: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:33:21,284: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:33:53,320: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:34:25,359: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:34:57,399: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:35:29,436: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:36:01,475: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:36:33,511: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:37:05,547: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:37:37,582: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:38:09,616: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:38:41,652: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:39:13,689: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:39:45,724: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:40:17,760: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379//: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 32.00 seconds... (16/100)

[2022-08-03 16:48:05,811: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 16:48:05,813: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 16:48:05,813: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 16:48:05,814: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 16:48:06,585: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-08-03 16:48:06,594: INFO/MainProcess] mingle: searching for neighbors
[2022-08-03 16:48:07,627: INFO/MainProcess] mingle: all alone
[2022-08-03 16:48:07,668: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-08-03 18:29:03,439: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 18:29:03,440: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 18:29:03,441: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 18:29:03,441: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 18:29:03,837: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-08-03 18:29:03,846: INFO/MainProcess] mingle: searching for neighbors
[2022-08-03 18:29:04,863: INFO/MainProcess] mingle: all alone
[2022-08-03 18:29:04,885: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-08-03 19:51:16,329: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 19:51:16,330: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 19:51:16,330: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 19:51:16,330: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-03 19:51:16,542: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-08-03 19:51:16,544: INFO/MainProcess] mingle: searching for neighbors
[2022-08-03 19:51:17,556: INFO/MainProcess] mingle: all alone
[2022-08-03 19:51:17,568: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-08-04 00:00:00,062: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': 'b4339942-b0bc-43d7-a538-880614f2d404', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'b4339942-b0bc-43d7-a538-880614f2d404', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen496143@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-08-04 00:00:00,286: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '55dc11f6-4657-4bf7-85c8-af86a3d9a934', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '55dc11f6-4657-4bf7-85c8-af86a3d9a934', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen496143@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-04 04:00:00,008: INFO/MainProcess] Task celery.backend_cleanup[d22ca45c-9599-46c2-a28f-5ad3af19c11f] received
[2022-08-05 00:00:00,009: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '05137719-1f95-42c0-b375-0a5d186a6eff', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '05137719-1f95-42c0-b375-0a5d186a6eff', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen496143@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-05 10:19:26,741: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-05 10:19:26,742: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-05 10:19:26,742: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-05 10:19:26,743: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-05 10:19:27,144: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-08-05 10:19:27,150: INFO/MainProcess] mingle: searching for neighbors
[2022-08-05 10:19:28,168: INFO/MainProcess] mingle: all alone
[2022-08-05 10:19:28,194: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-08-05 10:19:28,364: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': 'cc1d0567-0846-4456-af0d-c6cfc873ab18', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'cc1d0567-0846-4456-af0d-c6cfc873ab18', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen496143@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-08-05 10:19:28,469: INFO/MainProcess] Task celery.backend_cleanup[3cc96afd-4271-46b2-bf34-977927690756] received
[2022-08-05 10:19:28,472: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '134bee5c-b710-481b-8c24-9a29b89c882a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '134bee5c-b710-481b-8c24-9a29b89c882a', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen588310@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-05 10:19:28,549: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': '39b3161d-7dd6-4caf-8065-3c6b6c3095b1', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '39b3161d-7dd6-4caf-8065-3c6b6c3095b1', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen588310@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-08-05 10:19:28,631: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': 'f8d25850-bb46-4009-b36f-765b8239700d', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'f8d25850-bb46-4009-b36f-765b8239700d', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen588310@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-05 10:19:28,839: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': '82fbb7f7-93fd-4475-915c-0cbfac92e672', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '82fbb7f7-93fd-4475-915c-0cbfac92e672', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen496143@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-08-05 10:19:28,949: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '2fce8c88-411c-42c7-8511-a522a4fd5d66', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '2fce8c88-411c-42c7-8511-a522a4fd5d66', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen496143@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
