[2022-08-22 16:54:52,392: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:54:52,394: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:54:52,394: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:54:52,394: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:54:52,898: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-08-22 16:54:52,903: INFO/MainProcess] mingle: searching for neighbors
[2022-08-22 16:54:53,921: INFO/MainProcess] mingle: all alone
[2022-08-22 16:54:53,947: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-08-22 16:54:54,040: INFO/MainProcess] Task celery.backend_cleanup[eed20dbe-cd09-4ca5-bfe5-6d898e56e653] received
[2022-08-22 16:54:54,132: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '08a45c8b-68c8-4aa0-a343-6e41d965cdff', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '08a45c8b-68c8-4aa0-a343-6e41d965cdff', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1046695@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-22 16:54:54,255: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': 'd21d1fda-ebfc-42fc-9cc1-19f9ff9eadef', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'd21d1fda-ebfc-42fc-9cc1-19f9ff9eadef', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1046695@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-08-22 16:54:54,499: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': 'deff6bab-e10c-4b8e-91f6-a059128f0037', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'deff6bab-e10c-4b8e-91f6-a059128f0037', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1046695@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-22 16:54:54,577: INFO/MainProcess] Task celery.backend_cleanup[f09c694c-0e1b-4623-bbf0-db4aad3f374c] received
[2022-08-22 16:54:54,644: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '7e61b712-5872-4465-b782-680dbb70fe3a', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '7e61b712-5872-4465-b782-680dbb70fe3a', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1046796@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-22 16:54:54,710: ERROR/MainProcess] Received unregistered task of type 'ticker_management.views.syncDVSData'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.views.syncDVSData', 'id': 'c85c8090-5252-4f7f-98a0-d88a69f79d8b', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': 'c85c8090-5252-4f7f-98a0-d88a69f79d8b', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1046796@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.views.syncDVSData'
[2022-08-22 16:54:54,777: ERROR/MainProcess] Received unregistered task of type 'ticker_management.maintainLogs.filereader'.
The message has been ignored and discarded.

Did you remember to import the module containing this task?
Or maybe you're using relative imports?

Please see
http://docs.celeryq.org/en/latest/internals/protocol.html
for more information.

The full contents of the message body was:
b'[[], {}, {"callbacks": null, "errbacks": null, "chain": null, "chord": null}]' (77b)

Thw full contents of the message headers:
{'lang': 'py', 'task': 'ticker_management.maintainLogs.filereader', 'id': '2a8a3200-62b4-4954-b54b-2f9db2f3b742', 'shadow': None, 'eta': None, 'expires': None, 'group': None, 'group_index': None, 'retries': 0, 'timelimit': [None, None], 'root_id': '2a8a3200-62b4-4954-b54b-2f9db2f3b742', 'parent_id': None, 'argsrepr': '()', 'kwargsrepr': '{}', 'origin': 'gen1046796@rextermac', 'ignore_result': False}

The delivery info for this task is:
{'exchange': '', 'routing_key': 'celery'}
Traceback (most recent call last):
  File "/home/guest/Desktop/venv/lib/python3.8/site-packages/celery/worker/consumer/consumer.py", line 591, in on_task_received
    strategy = strategies[type_]
KeyError: 'ticker_management.maintainLogs.filereader'
[2022-08-22 16:58:07,452: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:58:07,453: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_RESULT_BACKEND' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the result_backend instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:58:07,453: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TIMEZONE' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the timezone instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:58:07,454: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/app/utils.py:204: CDeprecationWarning: 
    The 'CELERY_TASK_SERIALIZER' setting is deprecated and scheduled for removal in
    version 6.0.0. Use the task_serializer instead

  deprecated.warn(description=f'The {setting!r} setting',

[2022-08-22 16:58:07,881: INFO/MainProcess] Connected to redis://localhost:6379//
[2022-08-22 16:58:07,894: INFO/MainProcess] mingle: searching for neighbors
[2022-08-22 16:58:08,919: INFO/MainProcess] mingle: all alone
[2022-08-22 16:58:08,942: WARNING/MainProcess] /home/guest/Desktop/venv/lib/python3.8/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

