ERROR 2022-09-26 18:07:15,093 :  Error: TickerDetails matching query does not exist. from function detail in line no. 331 (FILENAME views)
ERROR 2022-09-27 11:28:42,793 :  Api call error: HTTPSConnectionPool(host='dvs-dev.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88382260d0>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 651 (FILENAME views)
ERROR 2022-09-27 11:28:42,953 :  Error: HTTPSConnectionPool(host='dvs-dev.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88382260d0>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-27 11:29:19,657 :  Api call error: HTTPSConnectionPool(host='dvs-dev.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8838b96430>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 651 (FILENAME views)
ERROR 2022-09-27 11:29:19,658 :  Error: HTTPSConnectionPool(host='dvs-dev.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8838b96430>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-27 11:30:27,241 :  Api call error: HTTPSConnectionPool(host='dvs-dev.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8838189b20>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function syncDVSData in line no. 651 (FILENAME views)
ERROR 2022-09-27 11:30:27,242 :  Error: HTTPSConnectionPool(host='dvs-dev.digivalet.com', port=443): Max retries exceeded with url: /dvs/api/key/selectR (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8838189b20>: Failed to establish a new connection: [Errno 110] Connection timed out')) from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-28 16:56:22,418 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-28 16:56:27,817 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-28 16:58:41,924 :  Error: SetUp matching query does not exist. from function syncDVSData in line no. 626 (FILENAME views)
ERROR 2022-09-28 16:59:45,217 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-28 17:01:07,192 :  SetUp matching query does not exist. from function syncDVSData in line no. 649 (FILENAME views)
ERROR 2022-09-28 17:01:45,716 :  SetUp matching query does not exist. from function syncDVSData in line no. 649 (FILENAME views)
ERROR 2022-09-28 17:02:33,180 :  SetUp matching query does not exist. from function syncDVSData in line no. 649 (FILENAME views)
ERROR 2022-09-28 17:02:33,181 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-28 17:03:05,950 :  SetUp matching query does not exist. from function syncDVSData in line no. 649 (FILENAME views)
ERROR 2022-09-28 17:03:05,953 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-28 17:04:10,622 :  Error: SetUp matching query does not exist. from function createTicker in line no. 103 (FILENAME views)
ERROR 2022-09-30 16:58:21,770 :  'list' object has no attribute 'replace' from function rundeck_update in line no. 78 (FILENAME rundecklog)
ERROR 2022-09-30 16:58:27,243 :  'list' object has no attribute 'replace' from function rundeck_update in line no. 78 (FILENAME rundecklog)
ERROR 2022-09-30 16:58:32,648 :  'list' object has no attribute 'replace' from function rundeck_update in line no. 78 (FILENAME rundecklog)
